version: '3'
services:
  user:
    build: ./user
    ports:
      - 8000:5000
  inventory:
    build: ./inventory
    ports:
      - 9000:5000
  web-app:
    build: ./web-app
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./web-app/public-html:/usr/local/apache2/htdocs  
